// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Employee.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Employee.Data.Configurations
{
    public partial class TblEmpInfoConfiguration : IEntityTypeConfiguration<TblEmpInfo>
    {
        public void Configure(EntityTypeBuilder<TblEmpInfo> entity)
        {
            entity.HasKey(e => e.EmpId)
                .HasName("PK__tblEmpIn__AF2DBB99AC5927F3");

            entity.ToTable("tblEmpInfo");

            entity.Property(e => e.Dept)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.EmailId)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.EmpAddress)
                .HasMaxLength(300)
                .IsUnicode(false);

            entity.Property(e => e.Mobile)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TblEmpInfo> entity);
    }
}
