// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Employee.Data.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
#nullable disable

namespace Employee.Data
{
    public partial class EmpdbContext : DbContext
    {
        public EmpdbContext()
        {
        }

        public EmpdbContext(DbContextOptions<EmpdbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TblEmpInfo> TblEmpInfo { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.TblEmpInfoConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
