// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Employee.Data
{
    public partial class TblEmpInfo
    {
        public int EmpId { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string EmailId { get; set; }
        public string EmpAddress { get; set; }
        public string Dept { get; set; }
        public int? Salary { get; set; }
    }
}